name: Makefile CI

on:
  push:
    branches: [ "main" ]
    tags:    [ "v*" ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential 

    - name: Build the project
      run: make

  release:
    runs-on: ubuntu-latest
    needs: build 

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*  # If your build creates any files (like binaries or zips), attach them here
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

